### ISSUE TITLE
vb crash on Windows

### ISSUE THREAD

**Issue by bgoodri** [stan-dev/stan#1758]
I can get a segfault on Windows from cmdstan (or rstan) with the following model / data / syntax
```
 ./weibull.exe variational data file=weibull.data.R random seed=1913258051
```

[weibull.txt](https://github.com/stan-dev/stan/files/101339/weibull.txt)
[weibull.data.txt](https://github.com/stan-dev/stan/files/101340/weibull.data.txt)

This seems to not be reproducible on Linux / Mac, although it is difficult to get meanfield to converge.

**Comment by bgoodri** [comment]
@akucukelbir or @dustinvtran Do you have access to a Windows machine to reproduce this? Change weibull.txt to weibull.stan and weibull.data.txt to weibull.data.R .

**Comment by dustinvtran** [comment]
Unfortunately no. :( I can see if it's possible to get it to converge, and maybe that would indirectly point us to where the problem is.

**Comment by akucukelbir** [comment]
negative on my end as well. no more windows in my life.

**Comment by bgoodri** [comment]
The backtrace is related to the streaming
```
#2  0x00514a70 in std::ostreambuf_iterator<char, std::char_traits<char> > std::num_put<char, std::ostreambuf_iterator<char, std::char_traits<char> > >::_M_insert_float<double>(std::ostreambuf_iterator<char, std::char_traits<char> >, std::ios_base&, char, char, double) const ()
```

**Comment by akucukelbir** [comment]
that, sadly, says nothing to me. :(

**Comment by bgoodri** [comment]
Sadly, that's all it says. But I think it means that it tried to print some
segfault inducing output to the screen rather than the variational
approximation process terminated unexpectedly. Possibly a string was too
long or had an illegal character in it.

**Comment by bob-carpenter** [comment]
Not a C++ whisperer yet?  You just need to be motivated
to parse everything out and type what you find into Google.

This:

> > #2 0x00514a70 in std::ostreambuf_iterator<char, std::char_traits<char> > std::num_put<char, std::ostreambuf_iterator<char, std::char_traits<char> > >::_M_insert_float<double>(std::ostreambuf_iterator<char, std::char_traits<char> >, std::ios_base&, char, char, double) const ()


is a function signature, which is revealed by reorganizing it a bit
(it helps to drop all the "std::", while you're at it):

RETURN TYPE:

  ostreambuf_iterator<char, 
                      char_traits<char> >

FUNCTION:

  num_put<char, 
          ostreambuf_iterator<char, 
                              char_traits<char> > >::_M_insert_float<double>


ARGUMENT TYPES:

  (ostreambuf_iterator<char,
                       char_traits<char> >, 
   ios_base&,
   char,
   char,
   double) 

CONST DECLARATION

  const ()


So we know to look up "std::num_put" (I couldn't live without
cplusplus.com):

  http://www.cplusplus.com/reference/locale/num_put/

So it's crashing at some point where it's trying to insert a double
into an output stream.  And it looks like its inheriting from a locale
somewhere, which is something that could easily vary across platforms.

The memory location's not too helpful (to me, at least).  I usually 
just try to bisect the code manually using print statements at this point,
but you need to  be able to recreate the error for that.  You could also
review all  the I/O if you have any other hint as to when the error occurs.

We have a Windows box in the office for just this kind of spelunking.

- Bob

**Comment by bgoodri** [comment]
What Bob said. I'm continuing to guess that it tried to stream a double
that was too big. If that is correct, could we use scientific notation or
something for the delta_ELBO_mean? It already looks weird when it uses
different numbers of digits to the left of the decimal point.

**Comment by akucukelbir** [comment]
i'm happy to look into using scientific notation for delta_ELBO_mean. i don't know how to test for this though... do either of you know how to test for these sorts of windows-only bugs?

**Comment by bgoodri** [comment]
We do have a Windows machine. You might be able to write a unit test that
just streams a million random characters in the same way that ADVI does.

**Comment by syclik** [comment]
@dustinvtran, @akucukelbir. Bump.
