### ISSUE TITLE
makefile bug - missing test model causes infinite loop in `runTests.py`

### ISSUE THREAD

**Issue by mitzimorris** [stan-dev/stan#2726]
#### Summary:
Missing test model causes `runTests.py` to go into an infinite loop when trying to run all unit tests in a directory.

#### Description:
If a unit test includes a Stan model, e.g., if unit test `src/test/unit/services/my_unit_test.cpp` has `#include` directive: 
```
#include <test/test-models/good/my_test_model.hpp
```
and the file `test/test-models/good/my_test_model.stan` is missing,  when `runTests.py` is invoked just on the unit test in question, e.g.,  
```
```
it correctly reports the problem and quits:
```
./runTests.py src/test/unit/services/util/gq_writer_test.cpp 
...

src/test/unit/services/util/gq_writer_test.cpp:7:10: fatal error: 'test/test-models/good/services/test_gq.hpp' file not found
#include <test/test-models/good/services/test_gq.hpp>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make: *** [test/unit/services/util/gq_writer_test.o] Error 1
make -j1 test/unit/services/util/gq_writer_test failed
exit now (01/11/19 10:26:39 EST)
```

But if invoked on an entire directory, it continues to try to compile the unit test, e.g.:

```
./runTests.py src/test/unit/services/util
...
clang++ -DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION -std=c++1y -Wno-unknown-warning-option -Wno-tautological-compare -Wno-sign-compare      -O0 -I src -I . -I lib/stan_math/ -I lib/stan_math/lib/eigen_3.3.3 -I lib/stan_math/lib/boost_1.66.0 -I lib/stan_math/lib/sundials_3.1.0/include -I lib/stan_math/lib/gtest_1.8.1/include -I lib/stan_math/lib/gtest_1.8.1     -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION    -DGTEST_USE_OWN_TR1_TUPLE  -c -MT test/unit/services/util/gq_writer_test.o -MT src/test/unit/services/util/gq_writer_test.d -MM -E -MG -MP -MF src/test/unit/services/util/gq_writer_test.d src/test/unit/services/util/gq_writer_test.cpp
clang++ -DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION -std=c++1y -Wno-unknown-warning-option -Wno-tautological-compare -Wno-sign-compare      -O0 -I src -I . -I lib/stan_math/ -I lib/stan_math/lib/eigen_3.3.3 -I lib/stan_math/lib/boost_1.66.0 -I lib/stan_math/lib/sundials_3.1.0/include -I lib/stan_math/lib/gtest_1.8.1/include -I lib/stan_math/lib/gtest_1.8.1     -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION    -DGTEST_USE_OWN_TR1_TUPLE  -c -MT test/unit/services/util/gq_writer_test.o -MT src/test/unit/services/util/gq_writer_test.d -MM -E -MG -MP -MF src/test/unit/services/util/gq_writer_test.d src/test/unit/services/util/gq_writer_test.cpp
clang++ -DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION -std=c++1y -Wno-unknown-warning-option -Wno-tautological-compare -Wno-sign-compare      -O0 -I src -I . -I lib/stan_math/ -I lib/stan_math/lib/eigen_3.3.3 -I lib/stan_math/lib/boost_1.66.0 -I lib/stan_math/lib/sundials_3.1.0/include -I lib/stan_math/lib/gtest_1.8.1/include -I lib/stan_math/lib/gtest_1.8.1     -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION    -DGTEST_USE_OWN_TR1_TUPLE  -c -MT test/unit/services/util/gq_writer_test.o -MT src/test/unit/services/util/gq_writer_test.d -MM -E -MG -MP -MF src/test/unit/services/util/gq_writer_test.d src/test/unit/services/util/gq_writer_test.cpp
clang++ -DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION -std=c++1y -Wno-unknown-warning-option -Wno-tautological-compare -Wno-sign-compare      -O0 -I src -I . -I lib/stan_math/ -I lib/stan_math/lib/eigen_3.3.3 -I lib/stan_math/lib/boost_1.66.0 -I lib/stan_math/lib/sundials_3.1.0/include -I lib/stan_math/lib/gtest_1.8.1/include -I lib/stan_math/lib/gtest_1.8.1     -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION    -DGTEST_USE_OWN_TR1_TUPLE  -c -MT test/unit/services/util/gq_writer_test.o -MT src/test/unit/services/util/gq_writer_test.d -MM -E -MG -MP -MF src/test/unit/services/util/gq_writer_test.d src/test/unit/services/util/gq_writer_test.cpp
clang++ -DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION -std=c++1y -Wno-unknown-warning-option -Wno-tautological-compare -Wno-sign-compare      -O0 -I src -I . -I lib/stan_math/ -I lib/stan_math/lib/eigen_3.3.3 -I lib/stan_math/lib/boost_1.66.0 -I lib/stan_math/lib/sundials_3.1.0/include -I lib/stan_math/lib/gtest_1.8.1/include -I lib/stan_math/lib/gtest_1.8.1     -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION    -DGTEST_USE_OWN_TR1_TUPLE  -c -MT test/unit/services/util/gq_writer_test.o -MT src/test/unit/services/util/gq_writer_test.d -MM -E -MG -MP -MF src/test/unit/services/util/gq_writer_test.d src/test/unit/services/util/gq_writer_test.cpp
clang++ -DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION -std=c++1y -Wno-unknown-warning-option -Wno-tautological-compare -Wno-sign-compare      -O0 -I src -I . -I lib/stan_math/ -I lib/stan_math/lib/eigen_3.3.3 -I lib/stan_math/lib/boost_1.66.0 -I lib/stan_math/lib/sundials_3.1.0/include -I lib/stan_math/lib/gtest_1.8.1/include -I lib/stan_math/lib/gtest_1.8.1     -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION    -DGTEST_USE_OWN_TR1_TUPLE  -c -MT test/unit/services/util/gq_writer_test.o -MT src/test/unit/services/util/gq_writer_test.d -MM -E -MG -MP -MF src/test/unit/services/util/gq_writer_test.d src/test/unit/services/util/gq_writer_test.cpp
clang++ -DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION -std=c++1y -Wno-unknown-warning-option -Wno-tautological-compare -Wno-sign-compare      -O0 -I src -I . -I lib/stan_math/ -I lib/stan_math/lib/eigen_3.3.3 -I lib/stan_math/lib/boost_1.66.0 -I lib/stan_math/lib/sundials_3.1.0/include -I lib/stan_math/lib/gtest_1.8.1/include -I lib/stan_math/lib/gtest_1.8.1     -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION    -DGTEST_USE_OWN_TR1_TUPLE  -c -MT test/unit/services/util/gq_writer_test.o -MT src/test/unit/services/util/gq_writer_test.d -MM -E -MG -MP -MF src/test/unit/services/util/gq_writer_test.d src/test/unit/services/util/gq_writer_test.cpp
clang++ -DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION -std=c++1y -Wno-unknown-warning-option -Wno-tautological-compare -Wno-sign-compare      -O0 -I src -I . -I lib/stan_math/ -I lib/stan_math/lib/eigen_3.3.3 -I lib/stan_math/lib/boost_1.66.0 -I lib/stan_math/lib/sundials_3.1.0/include -I lib/stan_math/lib/gtest_1.8.1/include -I lib/stan_math/lib/gtest_1.8.1     -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION    -DGTEST_USE_OWN_TR1_TUPLE  -c -MT test/unit/services/util/gq_writer_test.o -MT src/test/unit/services/util/gq_writer_test.d -MM -E -MG -MP -MF src/test/unit/services/util/gq_writer_test.d src/test/unit/services/util/gq_writer_test.cpp
clang++ -DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION -std=c++1y -Wno-unknown-warning-option -Wno-tautological-compare -Wno-sign-compare      -O0 -I src -I . -I lib/stan_math/ -I lib/stan_math/lib/eigen_3.3.3 -I lib/stan_math/lib/boost_1.66.0 -I lib/stan_math/lib/sundials_3.1.0/include -I lib/stan_math/lib/gtest_1.8.1/include -I lib/stan_math/lib/gtest_1.8.1     -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION    -DGTEST_USE_OWN_TR1_TUPLE  -c -MT test/unit/services/util/gq_writer_test.o -MT src/test/unit/services/util/gq_writer_test.d -MM -E -MG -MP -MF src/test/unit/services/util/gq_writer_test.d src/test/unit/services/util/gq_writer_test.cpp
^CTraceback (most recent call last):
  File "./runTests.py", line 36, in <module>
    main()
  File "./runTests.py", line 32, in main
    mathRunTests.main()
  File "/Users/mitzi/github/stan-dev/cmdstan/stan/lib/stan_math/runTests.py", line 166, in main
    makeTest(" ".join(batch), inputs.j)
  File "/Users/mitzi/github/stan-dev/cmdstan/stan/lib/stan_math/runTests.py", line 101, in makeTest
    doCommand('make -j%d %s' % (j or 1, name))
  File "/Users/mitzi/github/stan-dev/cmdstan/stan/lib/stan_math/runTests.py", line 89, in doCommand
    p1.wait()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1384, in wait
    pid, sts = _eintr_retry_call(os.waitpid, self.pid, 0)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 476, in _eintr_retry_call
    return func(*args)
KeyboardInterrupt
```
#### Reproducible Steps:

see above

#### Current Output:

see above

#### Expected Output:

`runTests.py` should detect problem and quit.

#### Current Version:
v2.18.1

**Comment by syclik** [comment]
Do you know what the script is doing?one hunting down the call to make and
I can try to debug from there.

**Comment by mitzimorris** [comment]
looks like the script is trying to compile the unit test  - I have unit test `src/test/unit/services/sample/standalone_gqs_test.cpp` which includes a model:
```
#include <test/test-models/good/services/bernoulli.hpp>
```
that's generated from file `stan/test/test-models/good/services/bernoulli.stan`

if I rename this file to `bernouilli.stan.hide` and run `make clean-all`,  then do ` runTests.py src/test/unit/services/sample`  `runTests.py` keeps attempting to compile the unit test over and over again:

```
clang++ -DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION -std=c++1y -Wno-unknown-warning-option -Wno-tautological-compare -Wno-sign-compare      -O0 -I src -I . -I lib/stan_math/ -I lib/stan_math/lib/eigen_3.3.3 -I lib/stan_math/lib/boost_1.66.0 -I lib/stan_math/lib/sundials_3.1.0/include -I lib/stan_math/lib/gtest_1.8.1/include -I lib/stan_math/lib/gtest_1.8.1     -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION    -DGTEST_USE_OWN_TR1_TUPLE  -c -MT test/unit/services/sample/standalone_gqs_test.o -MT src/test/unit/services/sample/standalone_gqs_test.d -MM -E -MG -MP -MF src/test/unit/services/sample/standalone_gqs_test.d src/test/unit/services/sample/standalone_gqs_test.cpp
clang++ -DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION -std=c++1y -Wno-unknown-warning-option -Wno-tautological-compare -Wno-sign-compare      -O0 -I src -I . -I lib/stan_math/ -I lib/stan_math/lib/eigen_3.3.3 -I lib/stan_math/lib/boost_1.66.0 -I lib/stan_math/lib/sundials_3.1.0/include -I lib/stan_math/lib/gtest_1.8.1/include -I lib/stan_math/lib/gtest_1.8.1     -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION    -DGTEST_USE_OWN_TR1_TUPLE  -c -MT test/unit/services/sample/standalone_gqs_test.o -MT src/test/unit/services/sample/standalone_gqs_test.d -MM -E -MG -MP -MF src/test/unit/services/sample/standalone_gqs_test.d src/test/unit/services/sample/standalone_gqs_test.cpp
clang++ -DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION -std=c++1y -Wno-unknown-warning-option -Wno-tautological-compare -Wno-sign-compare      -O0 -I src -I . -I lib/stan_math/ -I lib/stan_math/lib/eigen_3.3.3 -I lib/stan_math/lib/boost_1.66.0 -I lib/stan_math/lib/sundials_3.1.0/include -I lib/stan_math/lib/gtest_1.8.1/include -I lib/stan_math/lib/gtest_1.8.1     -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION    -DGTEST_USE_OWN_TR1_TUPLE  -c -MT test/unit/services/sample/standalone_gqs_test.o -MT src/test/unit/services/sample/standalone_gqs_test.d -MM -E -MG -MP -MF src/test/unit/services/sample/standalone_gqs_test.d src/test/unit/services/sample/standalone_gqs_test.cpp
^CTraceback (most recent call last):
  File "./runTests.py", line 36, in <module>
    main()
  File "./runTests.py", line 32, in main
    mathRunTests.main()
  File "/Users/mitzi/github/stan-dev/cmdstan/stan/lib/stan_math/runTests.py", line 166, in main
    makeTest(" ".join(batch), inputs.j)
  File "/Users/mitzi/github/stan-dev/cmdstan/stan/lib/stan_math/runTests.py", line 101, in makeTest
    doCommand('make -j%d %s' % (j or 1, name))
  File "/Users/mitzi/github/stan-dev/cmdstan/stan/lib/stan_math/runTests.py", line 89, in doCommand
    p1.wait()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1384, in wait
    pid, sts = _eintr_retry_call(os.waitpid, self.pid, 0)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 476, in _eintr_retry_call
    return func(*args)
KeyboardInterrupt
```

hope this helps.

**Comment by syclik** [comment]
Two questions:
What branch are you on?
What's the line that the runtests.py is actually using to invoke make?
(You're showing me the lines to clang++, but runtests.py must be calling
make with a target, no?)

**Comment by mitzimorris** [comment]
I'm on branch https://github.com/stan-dev/stan/tree/feature/2705-standalone-gqs-constrained-params-inputs

as far as I can tell runTests is calling make target:  `make -j%d %s`  - assuming `%s` is `test/unit/services/sample/standalone_gqs_test.o`

this is the unit test which is trying to import the Stan model.hpp file, where model file isn't in the test-models directory.

BTW, feel free to review PR https://github.com/stan-dev/stan/pull/2725 instead of working on this one.  ;-)

**Comment by syclik** [comment]
I wonder if it has to do with a call to the .o directly. We shouldn't be
doing that.

**Comment by syclik** [comment]
@mitzimorris, I just tried this and it didn't fail. Could you see if it's a problem now? Here's something you can run from the Stan folder (don't do this when you have uncommitted work):

```
git clean -dxf
pushd lib/stan_math
git clean -dxf
popd

echo '#include <gtest/gtest.h>
#include <test/test-models/good/my_test_model.hpp>

TEST(foo, bar) {
  SUCCEED();
}
' > src/test/unit/foo_test.cpp

./runTests.py src/test/unit/foo_test.cpp
```

This is what I see:
```
]$ ./runTests.py src/test/unit/foo_test.cpp
------------------------------------------------------------
make -j1 test/unit/foo_test
clang++ -std=c++1y -Wno-unknown-warning-option -Wno-tautological-compare -Wno-sign-compare      -O3 -I src -I . -I lib/stan_math/ -I lib/stan_math/lib/eigen_3.3.3 -I lib/stan_math/lib/boost_1.69.0 -I lib/stan_math/lib/sundials_4.1.0/include -I lib/stan_math/lib/gtest_1.8.1/include -I lib/stan_math/lib/gtest_1.8.1     -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION    -DGTEST_USE_OWN_TR1_TUPLE  -c -MT test/unit/foo_test.o -MT src/test/unit/foo_test.d -MM -E -MG -MP -MF src/test/unit/foo_test.d src/test/unit/foo_test.cpp
clang++ -std=c++1y -Wno-unknown-warning-option -Wno-tautological-compare -Wno-sign-compare      -O3 -I src -I . -I lib/stan_math/ -I lib/stan_math/lib/eigen_3.3.3 -I lib/stan_math/lib/boost_1.69.0 -I lib/stan_math/lib/sundials_4.1.0/include -I lib/stan_math/lib/gtest_1.8.1/include -I lib/stan_math/lib/gtest_1.8.1     -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION    -DGTEST_USE_OWN_TR1_TUPLE  -c -MT test/unit/foo_test.o -MT src/test/unit/foo_test.d -MM -E -MG -MP -MF src/test/unit/foo_test.d src/test/unit/foo_test.cpp
clang++ -std=c++1y -Wno-unknown-warning-option -Wno-tautological-compare -Wno-sign-compare      -O3 -I src -I . -I lib/stan_math/ -I lib/stan_math/lib/eigen_3.3.3 -I lib/stan_math/lib/boost_1.69.0 -I lib/stan_math/lib/sundials_4.1.0/include -I lib/stan_math/lib/gtest_1.8.1/include -I lib/stan_math/lib/gtest_1.8.1 -I lib/stan_math/lib/gtest_1.8.1/include -I lib/stan_math/lib/gtest_1.8.1      -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION    -DGTEST_USE_OWN_TR1_TUPLE -DGTEST_USE_OWN_TR1_TUPLE  -c src/test/unit/foo_test.cpp -o test/unit/foo_test.o
src/test/unit/foo_test.cpp:2:10: fatal error: 'test/test-models/good/my_test_model.hpp' file not found
#include <test/test-models/good/my_test_model.hpp>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make: *** [test/unit/foo_test.o] Error 1
make -j1 test/unit/foo_test failed
exit now (03/29/19 10:05:57 EDT)
```

And I've repeated that last call to runtests just to make sure it didn't pop up on the second call.

**Comment by mitzimorris** [comment]
did this:

```
  501  git checkout develop
  502  git pull
  503  git clean -dxf
  504  pushd lib/stan_math
  505  git clean -dxf
  506  popd
```

then created  `foo_test.cpp`, passed it as target to runTests.py, saw this:

```
~/github/stan-dev/cmdstan/stan (develop)> echo '#include <gtest/gtest.h>
> #include <test/test-models/good/my_test_model.hpp>
> 
> TEST(foo, bar) {
>   SUCCEED();
> }
> ' > src/test/unit/foo_test.cpp
~/github/stan-dev/cmdstan/stan (develop)> 
~/github/stan-dev/cmdstan/stan (develop)> ./runTests.py src/test/unit/foo_test.cpp
------------------------------------------------------------
make -j1 test/unit/foo_test
clang++ -std=c++1y -Wno-unknown-warning-option -Wno-tautological-compare -Wno-sign-compare      -O3 -I src -I . -I lib/stan_math/ -I lib/stan_math/lib/eigen_3.3.3 -I lib/stan_math/lib/boost_1.69.0 -I lib/stan_math/lib/sundials_4.1.0/include -I lib/stan_math/lib/gtest_1.8.1/include -I lib/stan_math/lib/gtest_1.8.1     -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION    -DGTEST_USE_OWN_TR1_TUPLE  -c -MT test/unit/foo_test.o -MT src/test/unit/foo_test.d -MM -E -MG -MP -MF src/test/unit/foo_test.d src/test/unit/foo_test.cpp
clang++ -std=c++1y -Wno-unknown-warning-option -Wno-tautological-compare -Wno-sign-compare      -O3 -I src -I . -I lib/stan_math/ -I lib/stan_math/lib/eigen_3.3.3 -I lib/stan_math/lib/boost_1.69.0 -I lib/stan_math/lib/sundials_4.1.0/include -I lib/stan_math/lib/gtest_1.8.1/include -I lib/stan_math/lib/gtest_1.8.1     -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION    -DGTEST_USE_OWN_TR1_TUPLE  -c -MT test/unit/foo_test.o -MT src/test/unit/foo_test.d -MM -E -MG -MP -MF src/test/unit/foo_test.d src/test/unit/foo_test.cpp
clang++ -std=c++1y -Wno-unknown-warning-option -Wno-tautological-compare -Wno-sign-compare      -O3 -I src -I . -I lib/stan_math/ -I lib/stan_math/lib/eigen_3.3.3 -I lib/stan_math/lib/boost_1.69.0 -I lib/stan_math/lib/sundials_4.1.0/include -I lib/stan_math/lib/gtest_1.8.1/include -I lib/stan_math/lib/gtest_1.8.1     -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION    -DGTEST_USE_OWN_TR1_TUPLE  -c -MT test/unit/foo_test.o -MT src/test/unit/foo_test.d -MM -E -MG -MP -MF src/test/unit/foo_test.d src/test/unit/foo_test.cpp
clang++ -std=c++1y -Wno-unknown-warning-option -Wno-tautological-compare -Wno-sign-compare      -O3 -I src -I . -I lib/stan_math/ -I lib/stan_math/lib/eigen_3.3.3 -I lib/stan_math/lib/boost_1.69.0 -I lib/stan_math/lib/sundials_4.1.0/include -I lib/stan_math/lib/gtest_1.8.1/include -I lib/stan_math/lib/gtest_1.8.1 -I lib/stan_math/lib/gtest_1.8.1/include -I lib/stan_math/lib/gtest_1.8.1      -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION    -DGTEST_USE_OWN_TR1_TUPLE -DGTEST_USE_OWN_TR1_TUPLE  -c src/test/unit/foo_test.cpp -o test/unit/foo_test.o
src/test/unit/foo_test.cpp:2:10: fatal error: 
      'test/test-models/good/my_test_model.hpp' file not found
#include <test/test-models/good/my_test_model.hpp>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make: *** [test/unit/foo_test.o] Error 1
make -j1 test/unit/foo_test failed
exit now (03/29/19 10:40:51 EDT)

```

**Comment by syclik** [comment]
Perfect. I'm closing this issue. Please open if you see this problem again.
