### ISSUE TITLE
Multi-Threaded log_prob function triggers segmentation fault

### ISSUE THREAD

**Issue by JohannesBuchner** [stan-dev/stan#538]
I thought it would be a brilliant idea to modify my likelihood function to do some parallelisation. I think this should work, but I get a segfault. Here is what I did.

Stan code of a sine wave problem with many data points

```
data {
    real measured[10000];
    real stdev;
}
parameters {
    real<lower=0.01,upper=10> ampl;
    real<lower=0.01,upper=10> freq;
    real<lower=0,upper=1> phi;
}
model {
    real m[10000];
    for (i in 1:10000) {
        m[i] <- ampl * sin((i * freq + phi) * 2 * pi());
    }
    measured ~ normal(m, stdev);
}
```

Data for this problem can be generated using this R code:

```
phi = 0.2
freq = 0.1
ampl = 1
stdev = 1
N = 10000
i = 1:N
mtrue = ampl * sin((i * freq + phi) * 2 * pi)
measured = rnorm(N, mean=mtrue,sd=stdev)
```

Now I generate the cpp code as usual. Then I modify two things: I include omp.h, and add a parallelisation to the loop that computes the sine model. Here is the diff:

```
@@ -1,5 +1,6 @@
 // Code generated by Stan version 2.0

+#include<omp.h>
 #include <stan/model/model_header.hpp>

 namespace parallel_model_namespace {
@@ -165,6 +166,7 @@
         {
             vector<T__> m(10000);
             stan::math::initialize(m, DUMMY_VAR__);
+            #pragma omp parallel for
             for (int i = 1; i <= 10000; ++i) {
                 stan::math::assign(get_base1_lhs(m,i,"m",1), (ampl * sin(((((i * freq) + phi) * 2) * pi()))));
             }
```

As you see, the content of the loop is very primitive, it just does a bit of computation and assignment to the vector.

I then compile, with the additional -fopenmp and -lgomp options in gcc:

```
g++ -fopenmp -lgomp -I src -isystem lib/eigen_3.2.0 -isystem lib/boost_1.54.0 -Wall -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS   -c -O3 -o parallel.o parallel.cpp && g++ -fopenmp -lgomp -I src -isystem lib/eigen_3.2.0 -isystem lib/boost_1.54.0 -Wall -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS  -lpthread  -O3 -o parallel_omp parallel.o -Lbin -lstan
```

However, when running (e.g. optimize) I get a segfault:

```
*** Error in `./parallel_omp': double free or corruption (!prev): 0x000000000153d0a0 ***
Segmentation fault
```

I believe the problem is when the T__ objects are copied, because if the loop is `for (int i = 1; i <= 10000; ++i) { m[i-1] = i; }` I can also trigger the problem.

I understand this is not exactly how I should use Stan, but it would be nice to get this working. I have a model with a long computation loop and it would be nice to use all processors on it, and OpenMP makes that easy.
It actually should work in my opinion, because that loop doesn't need to (de)allocate anything (beyond temporary variables). It would be great if you could have a look at this.

Here is the gdb backtrace if that helps at all:

```
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff4fa4700 (LWP 27852)]
__memmove_ssse3_back () at ../sysdeps/x86_64/multiarch/memcpy-ssse3-back.S:1630
1630    ../sysdeps/x86_64/multiarch/memcpy-ssse3-back.S: No such file or directory.
(gdb) backtrace
#0  __memmove_ssse3_back () at ../sysdeps/x86_64/multiarch/memcpy-ssse3-back.S:1630
#1  0x0000000000445f45 in std::__copy_move<false, true, std::random_access_iterator_tag>::__copy_m<stan::agrad::chainable*> (__first=<optimized out>, __last=__last@entry=0x6d62a0, 
    __result=__result@entry=0x7fffe80008c0)
    at /usr/lib/gcc/x86_64-pc-linux-gnu/4.7.3/include/g++-v4/bits/stl_algobase.h:366
#2  0x0000000000446067 in __copy_move_a<false, stan::agrad::chainable**, stan::agrad::chainable**> (
    __result=<optimized out>, __last=0x6d62a0, __first=<optimized out>)
    at /usr/lib/gcc/x86_64-pc-linux-gnu/4.7.3/include/g++-v4/bits/stl_algobase.h:384
#3  __copy_move_a2<false, stan::agrad::chainable**, stan::agrad::chainable**> (
    __result=<optimized out>, __last=0x6d62a0, __first=<optimized out>)
    at /usr/lib/gcc/x86_64-pc-linux-gnu/4.7.3/include/g++-v4/bits/stl_algobase.h:422
#4  copy<stan::agrad::chainable**, stan::agrad::chainable**> (__result=<optimized out>, 
    __last=0x6d62a0, __first=<optimized out>)
    at /usr/lib/gcc/x86_64-pc-linux-gnu/4.7.3/include/g++-v4/bits/stl_algobase.h:454
#5  __uninit_copy<stan::agrad::chainable**, stan::agrad::chainable**> (__result=<optimized out>, 
    __last=0x6d62a0, __first=<optimized out>)
    at /usr/lib/gcc/x86_64-pc-linux-gnu/4.7.3/include/g++-v4/bits/stl_uninitialized.h:95
#6  uninitialized_copy<stan::agrad::chainable**, stan::agrad::chainable**> (
    __result=<optimized out>, __last=0x6d62a0, __first=<optimized out>)
    at /usr/lib/gcc/x86_64-pc-linux-gnu/4.7.3/include/g++-v4/bits/stl_uninitialized.h:119
#7  __uninitialized_copy_a<stan::agrad::chainable**, stan::agrad::chainable**, stan::agrad::chainable*> (__result=<optimized out>, __last=0x6d62a0, __first=<optimized out>)
    at /usr/lib/gcc/x86_64-pc-linux-gnu/4.7.3/include/g++-v4/bits/stl_uninitialized.h:260
#8  __uninitialized_move_if_noexcept_a<stan::agrad::chainable**, stan::agrad::chainable**, std::allocator<stan::agrad::chainable*> > (__result=<optimized out>, __last=0x6d62a0, 
    __first=<optimized out>, __alloc=...)
    at /usr/lib/gcc/x86_64-pc-linux-gnu/4.7.3/include/g++-v4/bits/stl_uninitialized.h:283
#9  std::vector<stan::agrad::chainable*, std::allocator<stan::agrad::chainable*> >::_M_insert_aux (
    this=0x6befc0 <stan::agrad::var_stack_>, __position=, __x=@0x7ffff4fa3e68: 0x6bfad8)
    at /usr/lib/gcc/x86_64-pc-linux-gnu/4.7.3/include/g++-v4/bits/vector.tcc:363
#10 0x000000000040d5df in stan::agrad::var parallel_model_namespace::parallel_model::log_prob<true, true, stan::agrad::var>(std::vector<stan::agrad::var, std::allocator<stan::agrad::var> >&, std::vector<int, std::allocator<int> >&, std::ostream*) const [clone ._omp_fn.0] ()
    at /usr/lib/gcc/x86_64-pc-linux-gnu/4.7.3/include/g++-v4/bits/stl_vector.h:893
#11 0x00000039f6e090ea in gomp_thread_start (xdata=<optimized out>)
    at /mnt/data/tmp/portage/sys-devel/gcc-4.7.3-r1/work/gcc-4.7.3/libgomp/team.c:116
#12 0x0000003285e08f3a in start_thread (arg=0x7ffff4fa4700) at pthread_create.c:308
#13 0x00000032856eddad in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:113
```

**Comment by ariddell** [comment]
See stan-dev/math#551
